galaxy_info:
  role_name: monitoring_rsyslog
  author: "nodiscc <nodiscc@gmail.com>, Libre Logic <contact@libre-logic.fr>"
  description: "Log aggregation, processing and forwarding system"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
        - 11
    - name: Ubuntu
      versions:
        - 18.04
  galaxy_tags:
    - system
    - monitoring
    - syslog
    - rsyslog
    - logging
dependencies:
  - librelogic.librelogic.handlers
