
# apache will return a 403 error that will be logged when
# someone tries to access the root URL
- name: remove deprecated apache server index page
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/www/index.html
    - /var/www/logo.png
