##### CHECKS FOR OPENLDAP ROLE #####

- name: check that mandatory variables are correctly defined
  assert:
    that:
      - openldap_fqdn is not search("CHANGEME")
      - openldap_domain is not search("CHANGEME")
      - openldap_organization is not search("CHANGEME")
      - openldap_base_dn is not search("CHANGEME")
      - openldap_bind_username is not search("CHANGEME")
      - openldap_bind_password is not search("CHANGEME")
      - openldap_admin_password is not search("CHANGEME")
      - ldap_account_manager_allowed_hosts is not search(" ")
      - ldap_account_manager_fqdn is not search("CHANGEME")
      - ldap_account_manager_https_mode in ['selfsigned', 'letsencrypt']
      - ldap_account_manager_install_dir is not search("CHANGEME")
      - ldap_account_manager_install_method in ['tar.bz2']
      - ldap_account_manager_php_max_execution_time == ldap_account_manager_php_max_execution_time|int
      - ldap_account_manager_php_max_input_time == ldap_account_manager_php_max_input_time|int
      - ldap_account_manager_php_memory_limit|regex_search('[KMG]$')
      - ldap_account_manager_php_post_max_size|regex_search('[KMG]$')
      - ldap_account_manager_php_upload_max_filesize|regex_search('[KMG]$')
      - ldap_account_manager_session_timeout == ldap_account_manager_session_timeout|int
      - ldap_account_manager_version is defined
      - openldap_setup_lam == openldap_setup_lam|bool
