- name: add netdata http (ldap-account-manager/self-service-password)/process checks for openldap
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: netdata
    mode: 0640
  notify: assemble netdata configuration
  with_items:
    - src: etc_netdata_go.d_httpcheck.conf.d_openldap.conf.j2
      dest: /etc/netdata/go.d/httpcheck.conf.d/openldap.conf
    - src: etc_netdata_health.d_processes.conf.d_openldap.conf.j2
      dest: /etc/netdata/health.d/processes.conf.d/openldap.conf
