galaxy_info:
  role_name: monitoring_netdata
  author: "nodiscc <nodiscc@gmail.com>, Libre Logic <contact@libre-logic.fr>"
  description: "Lightweight real-time monitoring and alerting system"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 10
        - 11
    - name: Ubuntu
      versions:
        - 18.04
  galaxy_tags:
    - system
    - performance
    - monitoring
    - alerting
    - health
    - graphs
    - charts
dependencies:
  - librelogic.librelogic.handlers
