---

galaxy_info:
  role_name: common
  author: "Libre Logic"
  description: "Base setup tasks for Debian systems"
  license: "GPL-3.0"
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
    - name: Ubuntu
      versions:
        - 18.04
  galaxy_tags:
    - hostname
    - kernel
    - networking
    - swap
    - memory
    - sysctl
    - apt
    - debian
    - upgrades
    - pam
    - limits
    - ntp
    - time
    - date
    - ssh
    - hardening
    - utilities
    - users
    - sudo

dependencies: []
