---

galaxy_info:
  author: "Libre Logic"
  description: "Base setup tasks for Debian systems"
  company: 'Libre Logic'
  license: "GPL-3.0"
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
    - name: Ubuntu
      versions:
        - 18.04
  galaxy_tags:
    - apt
    - debian

dependencies: []
