- name: check that mandatory variables are correctly defined
  assert:
    quiet: yes
    that:
      - apache_enable_mod_evasive == apache_enable_mod_evasive|bool
      - apache_enable_service == apache_enable_service|bool
      - apache_letsencrypt_email is not search("CHANGEME")
      - apache_listen_http == apache_listen_http|bool
      - apache_allow_robots == apache_allow_robots|bool
      - apache_access_log_to_syslog == apache_access_log_to_syslog|bool
