- name: create ansible facts.d directory
  file:
    path: /etc/ansible/facts.d
    state: directory
    mode: 0755
  check_mode: no # create even in check mode so that following tasks don't fail

- name: create apache fact file
  template:
    src: etc_ansible_facts.d_apache.fact.j2
    dest: /etc/ansible/facts.d/apache.fact
    mode: 0644
  notify: update ansible facts
