##### APACHE MONITORING #####

- name: forward all www-data cron jobs mail to root
  lineinfile:
    path: /etc/aliases
    state: present
    create: yes
    regexp: "^www-data"
    line: "www-data: root"
    owner: root
    group: root
    mode: 0644

- name: configure rsyslog to aggregate apache access/error logs to syslog
  template:
    src: etc_rsyslog.d_{{ item }}.conf.j2
    dest: /etc/rsyslog.d/{{ item }}.conf
    owner: root
    group: root
    mode: 0644
  with_items:
    - apache
  notify: restart rsyslog

