- name: install netdata process check for apache
  template:
    src: etc_netdata_health.d_processes.conf.d_apache.conf.j2
    dest: /etc/netdata/health.d/processes.conf.d/apache.conf
    owner: root
    group: netdata
    mode: 0640
  notify: assemble netdata configuration
  ignore_errors: "{{ ansible_check_mode }}"