- name: configure rsyslog to aggregate apache error logs to syslog
  template:
    src: etc_rsyslog.d_apache.conf.j2
    dest: /etc/rsyslog.d/apache.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog
