##### LYNIS SECURITY AUDIT #####
# setup lynis security audit tool (yes/no)
setup_lynis: yes
# list of strings to extract from lynis reports and forward by mail
lynis_report_regex: 'warning|suggestion|manual'
# list of lynis tests to ignore/skip (https://cisofy.com/lynis/controls/)
lynis_skip_tests:
  - "CUST-0285" # Install libpam-usb to enable multi-factor authentication for PAM sessions (we don't use multi-factor auth for SSH)
  - "CUST-0830" # Install debian-goodies so that you can run checkrestart (needrestart is used instead)
  - "KRNL-5830" # Reboot required warnings are managed by netdata-needrestart
  - "BOOT-5122" # Password on GRUB bootloader to prevent altering boot configuration (access protected by physical security/hoster/hypervisor console password)
  - "AUTH-9286" # Configure minimum/maximum password age in /etc/login.defs (we don't enforce password aging)
  - "AUTH-9308" # No password set for single mode (access protected by physical security/hoster/hypervisor console password)
  - "FILE-6310" # place /tmp on a separated partition (root partition free disk space is monitored by netdata)
  - "TIME-3120" # Check ntpq peers output for unreliable ntp peers (we use a NTP pool, correct NTP peers wil be selected automatically)
  - "CONT-8104" # Run 'docker info' to see warnings applicable to Docker daemon (no swap support)
  - "AUTH-9283" # logins without password are denied by PAM and SSH (librelogic.librelogic.common)
  - "FIRE-4512" # broken check, does not detect firehol rules (https://github.com/CISOfy/lynis/issues/461, https://github.com/CISOfy/lynis/issues/767)
  - "DBS-1820" # ignore mongodb authentication check, mongodb is only listening on localhost
  - "PKGS-7392" # let debsecan manage/send detailed vulnerable package reports
  - "PHP-2372" # expose_php is only On in /etc/php/$version/cli/php.ini, Off for apache/php-fpm, returns false positives
# Allow known valid promiscuous interfaces
# N.B.: avoid special characters (like colon, equal, quote or double quote) in description.
# Example : 
#  - name: 'tap101i0'
#    description: 'Proxmox tap device (a software loopback device simulating an Ethernet NIC) backing the VM virtual NIC (VM id 101)'
lynis_allow_promiscuous_interfaces: []
# when to verify installed package files against MD5 checksums (daily/weekly/monthly/never)
debsums_cron_check: "daily"
