##### DOCKER CONTAINER ENGINE #####
# Docker release channel (stable/edge)
docker_apt_release_channel: stable
docker_apt_arch: amd64
# A list of users who will be added to the docker group
docker_users: []
# yes/no: start/stop docker service, enable/disable it on boot
docker_enable_service: yes
# the log driver for the docker daemon (none/local/json-file/syslog/journaled/gelf/fluentd/awslogs/splunk/etwlogs/gcplogs/logentries)
docker_log_driver: "syslog"
# docker swarm settings (accepts all parameters from https://docs.ansible.com/ansible/latest/collections/community/general/docker_swarm_module.html)
docker_swarm:
  state: "present"
# enable nightly prune of unused networks/images/stopped containers/build cache (yes/no)
docker_prune_nightly: yes
# allow docker to configure iptables rules automatically (yes/no)
docker_iptables: no
# Expected minimum/maximum number of running docker containers (if the host has the monitoring_netdata role)
# a list of additional hostname:IP mappings to include /etc/hosts inside containers
# extra_hosts: {{ docker_extra_hosts }} must be declared at the service level in docker stacks compose sections
docker_extra_hosts: []
# Example:
#docker_extra_hosts:
# - "somehost:162.242.195.82"
# - "otherhost:50.31.209.229"

# Docker Swarm labels to apply on host (dict):
docker_swarm_node_labels: {}
# Exemple:
# docker_swarm_node_labels:
#   has_volume_x: "true"
#   has_volume_y: "true"
#   has_service_z: "true"
