##### SELF-SIGNED CERTIFICATE GENERATION #####

- name: generate openssl private key
  openssl_privatekey:
    path: "/etc/docker/services-config/nginx/ssl/selfsigned/{{ mailcatcher_fqdn }}.key"
    owner: root
    group: root
    mode: 0600
  notify: restart nginx docker service

- name: generate openssl certificate signing request
  openssl_csr:
    path: "/etc/docker/services-config/nginx/ssl/selfsigned/{{ mailcatcher_fqdn }}.csr"
    privatekey_path: "/etc/docker/services-config/nginx/ssl/selfsigned/{{ mailcatcher_fqdn }}.key"
    common_name: "{{ mailcatcher_fqdn }}"
    owner: root
    group: root
    mode: 0644
  ignore_errors: "{{ ansible_check_mode }}"

- name: generate self-signed openssl certificate
  openssl_certificate:
    path: "/etc/docker/services-config/nginx/ssl/selfsigned/{{ mailcatcher_fqdn }}.crt"
    privatekey_path: "/etc/docker/services-config/nginx/ssl/selfsigned/{{ mailcatcher_fqdn }}.key"
    csr_path: "/etc/docker/services-config/nginx/ssl/selfsigned/{{ mailcatcher_fqdn }}.csr"
    provider: selfsigned
    owner: root
    group: root
    mode: 0644
  notify: restart nginx docker service
  ignore_errors: "{{ ansible_check_mode }}"

