##### PACKAGES #####

- name: install php-fpm packages
  apt:
    state: present
    package:
      - libapache2-mod-fcgid
      - php-apcu
      - php
      - php-fpm

- name: remove libapache2-mod-php
  apt:
    package:
      - libapache2-mod-php
      - libapache2-mod-php7.2
    state: absent
  notify: restart apache

##### CONFIGURATION #####

- name: detect php-fpm version
  set_fact:
    php_fpm_version: "{{ item.value }}"
  when: "{{ item.condition }}" # noqa no-jinja-when
  with_items:
    - { value: "7.3", condition: "ansible_distribution == 'Debian'" }
    - { value: "7.2", condition: "ansible_distribution == 'Ubuntu'" }

- name: copy php-fpm configuration
  template:
    src: "etc_php_7.3_fpm_pool.d_www.conf.j2"
    dest: "/etc/php/{{ php_fpm_version }}/fpm/pool.d/www.conf"
    mode: 0644
  notify:
    - restart php-fpm

- name: enable apache FastCGI module
  command: a2enmod proxy_fcgi
  args:
    creates: "/etc/apache2/mods-enabled/proxy_fcgi.load"
  notify: restart apache

- name: enable php-fpm configuration for apache
  command: a2enconf php{{ php_fpm_version }}-fpm
  args:
    creates: "/etc/apache2/conf-enabled/php{{ php_fpm_version }}-fpm.conf"
  notify: reload apache

##### SERVICE #####

- name: enable/disable start/stop php-fpm service
  systemd:
    name: php{{ php_fpm_version }}-fpm
    enabled: "{{ php_fpm_enable_service }}"
    state: "{{ 'started' if php_fpm_enable_service else 'stopped' }}"
  ignore_errors: "{{ ansible_check_mode }}"

##### FACT #####

- name: create ansible facts.d directory
  file:
    path: /etc/ansible/facts.d
    state: directory
    mode: 0755

- name: create php-fpm fact file
  template:
    src: etc_ansible_facts.d_php-fpm.fact.j2
    dest: /etc/ansible/facts.d/php-fpm.fact
    mode: 0644
  notify: update ansible facts
  ignore_errors: "{{ ansible_check_mode }}"
