### RSYSLOG LOG PROCESSING SYSTEM ###
# number of daily /var/log/syslog archives to retain
syslog_retention_days: 186
# yes/no: enable forwarding of syslog logs to a syslog server (over TLS/TCP)
rsyslog_enable_forwarding: no
# if forwarding is enabled, hostname/port to forward logs to
rsyslog_forward_to_hostname: "my.CHANGEME.org"
rsyslog_forward_to_port: 5140
# if forwarding is enabled, path to the syslog server CA certificate file
rsyslog_ssl_ca_cert_file: "data/certificates/logserver.CHANGEME.org"
