##### MONITORING #####

### LOGGING (RSYSLOG) ###
# setup rsyslog (aggregate application/service logs to /var/log/syslog, discard useless messages)
setup_rsyslog: yes
# number of daily /var/log/syslog archives to retain
syslog_retention_days: 186

### NETDATA MONITORING SYSTEM ###
# default interval between netdata updates (in seconds)
# each plugin/module can override this setting (but only to set a longer interval)
netdata_update_every: 2
# (MiB) amount of memory dedicated to caching metric values
netdata_dbengine_page_cache_size: 32
# (MiB) amount of disk space dedicated to storing Netdata metric values/metadata
netdata_dbengine_disk_space: 256
# space-separated list of IP addresses authorized to access netdata
netdata_allow_connections_from: '10.* 192.168.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.*'
# enable netdata cloud/SaaS features (yes/no)
netdata_cloud_enabled: no
# enable netdata self-monitoring charts/alarms (yes/no)
netdata_self_monitoring_enabled: no
# enable/disable netdata debug/error/access logs (yes/no)
netdata_disable_debug_log: yes
netdata_disable_error_log: no
netdata_disable_access_log: yes
# netdata installation method (binary/packagecloud)
netdata_install_method: 'binary'
# Netdata version (for netdata_install_method = binary) - https://github.com/netdata/netdata/releases/
netdata_version: "v1.32.0"

## NETDATA CHECKS ##
# Process checks
#   name: process group name to check (apps_groups.conf)
#   min_count: minimum expected number of processes
#   interval: time interval (seconds) between checks
# Example:
# netdata_process_checks:
#   - { name: ssh, min_count: 1, interval: 20} # SSH server
#   - { name: time, min_count: 1, interval: 20} # NTP daemon
#   - { name: fail2ban, min_count: 1, interval: 20} # bruteforce prevention/IPS
#   - { name: httpd, min_count: 1, interval: 20} # web server
#   - { name: sql, min_count: 1, interval: 20} # SQL database engine
#   - { name: gitea, min_count: 1, interval: 20} # gitea self-hosted software forge
#   - { name: gitlab_runner, min_count: 1, interval: 20} # gitlab CI job runner
#   - { name: ezstream, min_count: 1, interval: 20} # icecast/ezstream media streaming server
#   - { name: murmurd, min_count: 1, interval: 20} # mumble VoIP server
#   - { name: pulseaudio, min_count: 1, interval: 20} # pulseaudio network sound server
#   - { name: auth, min_count: 1, interval: 20} # openldap server
#   - { name: media, min_count: 1, interval: 20} # jellyfin media server
#   - { name: samba, min_count: 2, interval: 20} # samba file sharing server (smbd+nmbd)
netdata_process_checks: []
# HTTP checks
# uses the same syntax and parameters as netdata httpcheck module
# https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/httpcheck/
# https://github.com/netdata/go.d.plugin/blob/master/config/go.d/httpcheck.conf
# Example:
# netdata_http_checks:
#   - name: example.com
#     url: https://website.com:444
#     status_accepted:
#       - 200
#       - 401
#     tls_skip_verify: yes
#     timeout: 10
#     update_every: 20
netdata_http_checks: []
# X509/SSL/TLS certificate checks (time to expiration, revocation status)
# uses the same syntax and parameters as netdata x509check module
# Port is mandatory for all non-file schemes
# https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/x509check/
# https://github.com/netdata/go.d.plugin/blob/master/config/go.d/x509heck.conf
# Example:
# netdata_x509_checks:
#   - name example-org
#     source: https://example.org:443
#     days_until_expiration_critical: 15
#     timeout: 3
#     tls_skip_verify: yes
#     update_every: 20
netdata_x509_checks: []
# Netdata TCP port checks
#   name: readable name of the check
#   host: hostname or IP address to contact
#   ports: list of TCP port numbers to check
#   interval: time interval (seconds) between checks
# Example:
# netdata_port_checks:
#   - name: ldap-available
#     host: 192.168.10.10
#     ports: [389, 636]
#     interval: 10
netdata_port_checks: []
# Netdata file checks
# see https://raw.githubusercontent.com/netdata/go.d.plugin/master/config/go.d/filecheck.conf
netdata_file_checks: []
# Expected minimum/maximum number of running docker containers (if the host has the docker role)
netdata_min_running_docker_containers: '0'
netdata_max_running_docker_containers: '99999'

## NETDATA MODULES ##
# setup needrestart and netdata-needrestart module (yes/no)
setup_needrestart: yes
# automatically restart services that require it after an upgrade (yes/no)
needrestart_autorestart_services: no
# setup netdata-logcount module (yes/no)
setup_netdata_logcount: no
# (minutes) interval between updates of log message counts in the logcount module
netdata_logcount_update_interval: 1
# maximum acceptable ERROR message in logs over the last period before raising a WARNING or CRITICAL alert
netdata_logcount_error_threshold_warn: 10
netdata_logcount_error_threshold_crit: 100
# maximum acceptable WARNING message in logs over the last period before raising a WARNING alert
netdata_logcount_warning_threshold_warn: 10
# user to send logcount notifications to (eg. sysadmin, silent...)
netdata_logcount_notification_to: "silent"
# setup netdata-debsecan module (yes/no)
setup_netdata_debsecan: no

### CLI MONITORING UTILITIES ###
# install ncdu, nethogs, htop, lnav (yes/no)
setup_monitoring_cli_utils: yes


##### LYNIS SECURITY AUDIT #####
# setup lynis security audit tool (yes/no)
setup_lynis: yes
# list of strings to extract from lynis reports and forward by mail
lynis_report_regex: 'warning|suggestion|manual'
# list of lynis tests to ignore/skip (https://cisofy.com/lynis/controls/)
lynis_skip_tests:
  - "CUST-0285" # Install libpam-usb to enable multi-factor authentication for PAM sessions (we don't use multi-factor auth for SSH)
  - "CUST-0830" # Install debian-goodies so that you can run checkrestart (needrestart is used instead)
  - "BOOT-5122" # Password on GRUB bootloader to prevent altering boot configuration (access protected by physical security/hoster/hypervisor console password)
  - "AUTH-9286" # Configure minimum/maximum password age in /etc/login.defs (we don't enforce password aging)
  - "AUTH-9308" # No password set for single mode (access protected by physical security/hoster/hypervisor console password)
  - "FILE-6310" # place /tmp on a separated partition (root partition free disk space is monitored by netdata)
  - "TIME-3120" # Check ntpq peers output for unreliable ntp peers (we use a NTP pool, correct NTP peers wil be selected automatically)
  - "CONT-8104" # Run 'docker info' to see warnings applicable to Docker daemon (no swap support)
  - "AUTH-9283" # logins without password are denied by PAM and SSH (librelogic.librelogic.common)
  - "FIRE-4512" # broken check, does not detect firehol rules (https://github.com/CISOfy/lynis/issues/461, https://github.com/CISOfy/lynis/issues/767)
  - "DBS-1820" # ignore mongodb authentication check, mongodb is only listening on localhost