##### LYNIS SECURITY AUDIT #####

- name: install lynis
  apt:
    package: lynis
    state: present

- name: copy custom lynis scan profile
  template:
    src: etc_lynis_custom.prf.j2
    dest: /etc/lynis/custom.prf
    owner: root
    group: root
    mode: 0640

- name: setup lynis daily cron job
  cron:
    cron_file: lynis
    hour: "21"
    minute: "0"
    day: "*"
    name: "daily lynis audit"
    job: >
      /usr/sbin/lynis audit system --profile /etc/lynis/custom.prf --warnings-only --cronjob --report-file /var/log/lynis-report.txt >/dev/null &&
      grep -i -E '{{ lynis_report_regex }}' /var/log/lynis-report.txt
    user: root
