- include: netdata.yml
  become: yes
  tags:
    - monitoring
    - netdata

- include: monitoring.yml
  become: yes
  tags:
    - monitoring

- include: lynis.yml
  become: yes
  tags:
    - monitoring
    - lynis
  when: setup_lynis|bool

- include: rsyslog.yml
  become: yes
  tags:
    - monitoring
    - syslog
    - rsyslog
