### NETDATA-MODTIME ###

- name: clone netdata-modtime module
  git:
    dest: "/root/netdata-modtime"
    repo: "https://gitlab.com/nodiscc/netdata-modtime"
    version: "0.1.0"
    accept_hostkey: yes
    force: yes # discard modified files

- name: install netdata-modtime module
  copy:
    remote_src: yes
    src: "/root/netdata-modtime/modtime.chart.py"
    dest: "/usr/libexec/netdata/python.d/modtime.chart.py"
    owner: root
    group: netdata
    mode: 0750
  notify: restart netdata
  when: not ansible_check_mode

- name: copy configuration for netdata-modtime
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: netdata
    mode: 0640
  with_items:
    - src: 'etc_netdata_python.d_modtime.conf.d_000-modtime.conf.j2'
      dest: '/etc/netdata/python.d/modtime.conf.d/000-modtime.conf'
    - src: 'etc_netdata_health.d_modtime.conf.d_000-modtime.conf.j2'
      dest: '/etc/netdata/health.d/modtime.conf.d/000-modtime.conf'
  notify: assemble netdata configuration
