- name: install rsyslog
  apt:
    state: present
    package:
      - rsyslog

- name: set retention/rotation policy for rsyslog logs
  template:
    src: etc_logrotate.d_rsyslog.j2
    dest: /etc/logrotate.d/rsyslog
    mode: 0644

- name: configure rsyslog
  template:
    src: etc_rsyslog.d_{{ item }}.conf.j2
    dest: /etc/rsyslog.d/{{ item }}.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog
  with_items:
    - 000-discard # discard useless messages
    - 000-singlefile # log all messages to /var/log/syslog
    - 000-imfile # load the imfile (text file input) module used by other roles
    - fail2ban # fail2ban logs aggregation
    - apt # apt logs aggregation

# DEPRECATED this task will be removed in a future version of the role
- name: remove rsyslog config files from old versions of the role
  file:
    state: absent
    path: /etc/rsyslog.d/{{ item }}.conf
  notify: restart rsyslog
  with_items:
    - services-imfile
    - discard
    - singlefile
    - netdata

# rsyslog is configured to send all messages to /var/log/syslog in singlefile.conf
# if a '*.*' filter is present in main rsyslog.conf, messages will be logged twice
- name: configure rsyslog to avoid duplicate messages
  lineinfile:
    path: /etc/rsyslog.conf
    state: absent
    regexp: '^\*\.\*'
  notify: restart rsyslog
