---

- name: check if letsencrypt certificate already exists for the servername
  become: yes
  stat:
    path: "/etc/letsencrypt/live/{{ item.servername }}/cert.pem"
  register: letsencrypt_cert
  when: item.cert_mode == 'letsencrypt'

- name: stop nginx to allow certbot standalone server to bind to port 80
  become: yes
  command: docker service scale nginx-reverseproxy_nginx-reverseproxy=0
  when:
   - item.cert_mode == 'letsencrypt'
   - not letsencrypt_cert.stat.exists
  failed_when: false # ignore errors since the service will not exist yet on first run

- name: wait 5 seconds to allow the nginx docker service to terminate
  wait_for:
    timeout: 5

- name: generate initial letsencrypt certificate
  become: yes
  command: >
    certbot certonly --standalone --noninteractive --agree-tos
    --email "{{ nginx_letsencrypt_email | default('admin@' + item.servername) }}"
    -d "{{ item.servername }}"
  when:
    - item.cert_mode == 'letsencrypt'
    - not letsencrypt_cert.stat.exists
