---

##### HOSTNAME ####

- name: set hostname
  hostname: name={{ inventory_hostname }}
  tags: common-hostname
  when: setup_hostname|bool

- name: update /etc/hosts with new hostname
  lineinfile:
    dest: '/etc/hosts'
    line: '{{ item }}	{{ inventory_hostname }}' # noqa 203
    regexp: '^{{ item }}'
  with_items:
    - '127.0.1.1'
  tags: common-hostname
  when: setup_hostname|bool

##### KERNEL CONFIGURATION #####

- name: copy sysctl configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: 'etc_sysctl.d_99-networking.conf.j2', dest: '/etc/sysctl.d/99-networking.conf' }
    - { src: 'etc_sysctl.d_99-memory-mgmt.conf.j2', dest: '/etc/sysctl.d/99-memory-mgmt.conf' }
    - { src: 'etc_sysctl.d_99-misc-security.conf.j2', dest: '/etc/sysctl.d/99-misc-security.conf' }
  tags: common-sysctl
  notify: apply sysctl configuration
  when:
    - setup_sysctl|bool

# apply sysctl configuration when config files have changed
- name: run all notified handlers
  meta: flush_handlers

