- name: check that mandatory variables are correctly defined
  assert:
    quiet: yes
    that:
      - dns_nameservers|type_debug == "list"
      - linux_users|type_debug == "list"
      - os_security_kernel_enable_core_dump == os_security_kernel_enable_core_dump|bool
      - setup_apt == setup_apt|bool
      - apt_unattended_upgrades_origins_patterns|type_debug == "list"
      - setup_cli_utils == setup_cli_utils|bool
      - setup_cron == setup_cron|bool
      - setup_dns == setup_dns|bool
      - setup_hostname == setup_hostname|bool
      - setup_firewall == setup_firewall|bool
      - setup_fail2ban == setup_fail2ban|bool
      - setup_haveged == setup_haveged|bool
      - setup_msmtp == setup_msmtp|bool
      - apt_listbugs == apt_listbugs|bool
      - setup_ssh == setup_ssh|bool
      - ssh_permit_root_login in ['yes', 'no', 'without-password', 'prohibit-password', 'forced-commands-only']
      - setup_datetime == setup_datetime|bool
      - setup_sysctl == setup_sysctl|bool
      - ssh_allow_tcp_forwarding in ['no', 'local', 'remote', 'all']
      - ssh_authorized_keys|type_debug == "list"
      - ssh_log_level in ['QUIET', 'FATAL', 'ERROR', 'INFO', 'VERBOSE', 'DEBUG', 'DEBUG1', 'DEBUG2', 'DEBUG3']
      - ssh_server_revoked_keys|type_debug == "list"
      - ssh_sftp_loglevel in ['QUIET', 'FATAL', 'ERROR', 'INFO', 'VERBOSE', 'DEBUG', 'DEBUG1', 'DEBUG2', 'DEBUG3']
      - sysctl_allow_forwarding == sysctl_allow_forwarding|bool
      - sysctl_answer_ping == sysctl_answer_ping|bool
      - sysctl_vm_swappiness|int
      - sysctl_vm_vfs_cache_pressure|int
      - setup_users == setup_users|bool
    success_msg: "Role variables are correctly defined."
    fail_msg: "One or more variables are not correctly defined. Check role documentation."

- name: check that mandatory variables are correctly defined (msmtp)
  assert:
    quiet: yes
    that:
      - msmtp_smtp_host is not search("CHANGEME")
      - msmtp_smtp_port == msmtp_smtp_port|int
      - msmtp_auth_enabled == msmtp_auth_enabled|bool
      - msmtp_tls_enabled == msmtp_tls_enabled|bool
      - msmtp_admin_email is not search("CHANGEME")
      - msmtp_from is not search("CHANGEME")
      - msmtp_auth_enabled == msmtp_auth_enabled|bool
      - msmtp_tls_enabled == msmtp_tls_enabled|bool
      - msmtp_starttls == msmtp_starttls|bool
      - msmtp_tls_certcheck == msmtp_tls_certcheck|bool
      - msmtp_starttls == msmtp_starttls|bool
  when: setup_msmtp|bool
  tags:
    - mail
    - msmtp

- name: check that mandatory variables are correctly defined (msmtp authentication)
  assert:
    quiet: yes
    that:
      - msmtp_smtp_user is not search("CHANGEME")
      - msmtp_smtp_password is not search("CHANGEME")
  when:
    - setup_msmtp|bool
    - msmtp_auth_enabled|bool
  tags:
    - mail
    - msmtp
