---

##### MSMTP SMTP CLIENT #####

- name: install msmtp SMTP client
  apt:
    package:
      - msmtp
      - msmtp-mta
    state: present
    update_cache: true
    cache_valid_time: 900

- name: copy msmtp configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "etc_msmtprc.j2", dest: "/etc/msmtprc" }
    - { src: "etc_aliases.j2", dest: "/etc/aliases" }

- name: remove legacy msmtp configuration files
  file:
    path: "/etc/msmtp-aliases"
    state: absent