---

##### EXTRA PACKAGES/UTILITIES #####

- name: install other packages/command-line utilities
  apt:
    package:
      - rsync # fast file transfer/synchronization utility
      - htop # ncurses resources monitor - useful for interactive process management/performance checks
      - at # task cheduler - required for ansible at module/interactive one-shot job scheduling
      - git # distributed version control system - required for ansible git module
    state: present
