- name: restart php-fpm
  service:
    name: php{{ php_fpm_version }}-fpm
    state: restarted
    enabled: yes
  become: yes
  when: php_fpm_enable_service|bool
  ignore_errors: "{{ ansible_check_mode }}"

- name: update ansible facts
  setup:
