galaxy_info:
  role_name: apache
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Apache web server/reverse proxy"
  license: "GPL-3.0"
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 10
        - 11
    - name: Ubuntu
      versions:
        - 18.04
  galaxy_tags:
    - web
    - webserver
    - reverseproxy
    - apache
dependencies: []
#  - librelogic.librelogic.common # optional
