##### SERVICE CONTROL #####

# roles that need to install their own imfile/other rsyslog configuration should create a file
# '/etc/rsyslog.d/COMPONENT_NAME.conf' and notify the 'restart rsyslog' handler
- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: assemble netdata configuration
  become: yes
  assemble:
    src: /etc/netdata/{{ item }}.d
    dest: /etc/netdata/{{ item }}
    owner: root
    group: netdata
    mode: 0640
  with_items:
    - go.d/filecheck.conf
    - go.d/httpcheck.conf
    - go.d/x509check.conf
    - go.d/portcheck.conf
    - health.d/filecheck.conf
    - health.d/processes.conf
  notify: restart netdata
  ignore_errors: "{{ ansible_check_mode }}"

- name: restart netdata
  become: yes
  service:
    name: netdata
    state: restarted
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: re-execute the systemd manager
  become: yes
  systemd:
    daemon_reexec: yes
